---
apiVersion: v1
kind: Pod
metadata:
  name: posts-pod
  labels:
    name: posts-pod
    context: springboot-k8s
    app: web
spec:
  containers:
    - name: rest-service
      image: springio:SpringBootRestApiPosts
      ports:
        - containerPort: 8090
