---
apiVersion: v1
kind: Service
metadata:
  name: posts-service
  labels:
    name: posts-service
    context: springboot-k8s
spec:
  ports:
    # the port that this service should serve on
    - port: 8090
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: posts-pod
    context: springboot-k8s


